if status is-interactive
    # Commands to run in interactive sessions can go here
    starship init fish | source
end
abbr -a -- gdf 'git diff'
abbr -a -- gst 'git status'
abbr -a -- gst 'git status'
abbr -a -- gpl 'git pull'
abbr -a -- gps 'git push'
abbr -a -- gpuo 'git push --set-upstream origin'
abbr -a -- gs 'git switch'
abbr -a -- gsc 'git switch -c'
abbr -a -- gcam 'git commit -am "'
abbr -a -- gcp 'git cherry-pick'
abbr -a -- gr 'git rebase'
abbr -a -- gm 'git merge'
abbr -a --position anywhere -- HEAD 'HEAD~'
abbr -a -- gst 'git status'
abbr -a -- gpl 'git pull'
abbr -a -- gps 'git push'
abbr -a -- gpuo 'git push --set-upstream origin'
abbr -a -- gs 'git switch'
abbr -a -- gsc 'git switch -c'
abbr -a -- gcam 'git commit -am "'
abbr -a -- gcp 'git cherry-pick'
abbr -a -- gr 'git rebase'
abbr -a -- gm 'git merge'
abbr -a --position anywhere -- HEAD 'HEAD~'
abbr -a -- glo 'git log --oneline'
abbr -a -- gst 'git status'
abbr -a -- gpl 'git pull'
abbr -a -- gps 'git push'
abbr -a -- gpuo 'git push --set-upstream origin'
abbr -a -- gs 'git switch'
abbr -a -- gsc 'git switch -c'
abbr -a -- gcam 'git commit -am "'
abbr -a -- gcp 'git cherry-pick'
abbr -a -- gr 'git rebase'
abbr -a -- gm 'git merge'
abbr -a --position anywhere -- HEAD 'HEAD~'
abbr -a -- glo 'git log --oneline'
abbr -a -- ga 'git add'
abbr -a -- gst 'git status'
abbr -a -- gpl 'git pull'
abbr -a -- gps 'git push'
abbr -a -- gpuo 'git push --set-upstream origin'
abbr -a -- gs 'git switch'
abbr -a -- gsc 'git switch -c'
abbr -a -- gcam 'git commit -am "'
abbr -a -- gcp 'git cherry-pick'
abbr -a -- gr 'git rebase'
abbr -a -- gm 'git merge'
abbr -a --position anywhere -- HEAD 'HEAD~'
abbr -a -- glo 'git log --oneline'
abbr -a -- ga 'git add'
abbr -a -- gcm 'git commit -m'
abbr -a -- gst 'git status'
abbr -a -- gpl 'git pull'
abbr -a -- gps 'git push'
abbr -a -- gpuo 'git push --set-upstream origin'
abbr -a -- gs 'git switch'
abbr -a -- gsc 'git switch -c'
abbr -a -- gcam 'git commit -am "'
abbr -a -- gcp 'git cherry-pick'
abbr -a -- gr 'git rebase'
abbr -a -- gm 'git merge'
abbr -a --position anywhere -- HEAD 'HEAD~'
abbr -a -- glo 'git log --oneline'
abbr -a -- ga 'git add'
abbr -a -- gcm 'git commit -m'
abbr -a -- gsm 'git switch main'
abbr -a -- gsh 'git stash'
abbr -a -- gsp 'git stash pop'
abbr -a -- gst 'git status'
abbr -a -- gpl 'git pull'
abbr -a -- gps 'git push'
abbr -a -- gpuo 'git push --set-upstream origin'
abbr -a -- gs 'git switch'
abbr -a -- gsc 'git switch -c'
abbr -a -- gcam 'git commit -am "'
abbr -a -- gcp 'git cherry-pick'
abbr -a -- gr 'git rebase'
abbr -a -- gm 'git merge'
abbr -a --position anywhere -- HEAD 'HEAD~'
abbr -a -- glo 'git log --oneline'
abbr -a -- ga 'git add'
abbr -a -- gcm 'git commit -m'
abbr -a -- gsm 'git switch main'
abbr -a -- gsh 'git stash'
abbr -a -- gsp 'git stash pop'
abbr -a -- prim 'npm run prisma:migrate'
abbr -a -- gst 'git status'
abbr -a -- gpl 'git pull'
abbr -a -- gps 'git push'
abbr -a -- gpuo 'git push --set-upstream origin'
abbr -a -- gs 'git switch'
abbr -a -- gsc 'git switch -c'
abbr -a -- gcam 'git commit -am "'
abbr -a -- gcp 'git cherry-pick'
abbr -a -- gr 'git rebase'
abbr -a -- gm 'git merge'
abbr -a --position anywhere -- HEAD 'HEAD~'
abbr -a -- glo 'git log --oneline'
abbr -a -- ga 'git add'
abbr -a -- gcm 'git commit -m'
abbr -a -- gsm 'git switch main'
abbr -a -- gsh 'git stash'
abbr -a -- gsp 'git stash pop'
abbr -a -- prim 'npm run prisma:migrate'
abbr -a -- nrd 'npm run dev'
abbr -a -- gst 'git status'
abbr -a -- gpl 'git pull'
abbr -a -- gps 'git push'
abbr -a -- gpuo 'git push --set-upstream origin'
abbr -a -- gs 'git switch'
abbr -a -- gsc 'git switch -c'
abbr -a -- gcam 'git commit -am "'
abbr -a -- gcp 'git cherry-pick'
abbr -a -- gr 'git rebase'
abbr -a -- gm 'git merge'
abbr -a --position anywhere -- HEAD 'HEAD~'
abbr -a -- glo 'git log --oneline'
abbr -a -- ga 'git add'
abbr -a -- gcm 'git commit -m'
abbr -a -- gsm 'git switch main'
abbr -a -- gsh 'git stash'
abbr -a -- gsp 'git stash pop'
abbr -a -- prim 'npm run prisma:migrate'
abbr -a -- nrd 'npm run dev'
abbr -a -- mig 'npm run prisma:migrate'
abbr -a -- gst 'git status'
abbr -a -- gpl 'git pull'
abbr -a -- gps 'git push'
abbr -a -- gpuo 'git push --set-upstream origin'
abbr -a -- gs 'git switch'
abbr -a -- gsc 'git switch -c'
abbr -a -- gcam 'git commit -am "'
abbr -a -- gcp 'git cherry-pick'
abbr -a -- gr 'git rebase'
abbr -a -- gm 'git merge'
abbr -a --position anywhere -- HEAD 'HEAD~'
abbr -a -- glo 'git log --oneline'
abbr -a -- ga 'git add'
abbr -a -- gcm 'git commit -m'
abbr -a -- gsm 'git switch main'
abbr -a -- gsh 'git stash'
abbr -a -- gsp 'git stash pop'
abbr -a -- prim 'npm run prisma:migrate'
abbr -a -- nrd 'npm run dev'
abbr -a -- mig 'npm run prisma:migrate'
abbr -a -- nrdl 'npm run dev:livelog'
fish_add_path $HOME/.local/bin
